backend:
  name: github
  repo: margaretkrutikova/margareta.dev

local_backend: true

media_folder: static/assets
public_folder: assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { name: path, label: Path, optional: true }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: published, label: Published, widget: "boolean", default: false }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    path: "{{language}}/{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { name: path, label: Path, optional: true }
      - { name: date, label: Date, widget: date }
      - { name: category, default: "notes" }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: language, label: Language }
      - { name: tags, label: Tags, widget: "list" }
      - { name: body, label: Body, widget: markdown }
